name: Sync Deploy

on:
  workflow_dispatch:
  schedule:
  - cron: '30 19 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2

      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set ENV
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
            mkdir -p ~/.ssh/
            echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
            chmod 700 ~/.ssh
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email josricor@outlook.com
            git config --global user.name josricor
            yarn && yarn build

      - name: Deploy GitHub Pages
        run: |
          npm i -g gh-pages
          gh-pages -d dist -r git@github.com:Sricor/Sricor.github.io.git -b main -f
