name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Set ENV
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email josricor@outlook.com
          git config --global user.name josricor
          
    - name: Deploy
      run: |
        yarn && yarn build
        yarn add gh-pages
        yarn gh-pages -d dist -r git@github.com:Sricor/Portfolio.git -f
        
