name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: deploy
      run: |
        git config --global user.email josricor@outlook.com
        git config --global user.name josricor
        yarn && yarn build
        cd dist && git add .
        git commit -m "deploy"
        git push gh-pages -f
